CREATE TABLE plan_element_item
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text            TEXT                                    NOT NULL,
    plan_element_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_plan_element_item PRIMARY KEY (id)
);

CREATE TABLE presentation_plan
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    short_description TEXT                                    NOT NULL,
    slides_count      INTEGER                                 NOT NULL,
    CONSTRAINT pk_presentation_plan PRIMARY KEY (id)
);

CREATE TABLE presentation_plan_element
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                VARCHAR(255)                            NOT NULL,
    presentation_plan_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_presentation_plan_element PRIMARY KEY (id)
);

ALTER TABLE plan_element_item
    ADD CONSTRAINT FK_PLAN_ELEMENT_ITEM_ON_PLAN_ELEMENT FOREIGN KEY (plan_element_id) REFERENCES presentation_plan_element (id);

ALTER TABLE presentation_plan_element
    ADD CONSTRAINT FK_PRESENTATION_PLAN_ELEMENT_ON_PRESENTATION_PLAN FOREIGN KEY (presentation_plan_id) REFERENCES presentation_plan (id);