CREATE TABLE presentation_plan
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    short_description TEXT                                    NOT NULL,
    slides_count      INTEGER                                 NOT NULL,
    elements          JSONB                                   NOT NULL,
    CONSTRAINT pk_presentation_plan PRIMARY KEY (id)
);