CREATE TABLE image
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_image PRIMARY KEY (id)
);

CREATE TABLE presentation
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                     VARCHAR(255)                            NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at               TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    template_presentation_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_presentation PRIMARY KEY (id)
);

CREATE TABLE presentation_plan
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    short_description TEXT                                    NOT NULL,
    slides_count      INTEGER                                 NOT NULL,
    elements          JSONB                                   NOT NULL,
    CONSTRAINT pk_presentation_plan PRIMARY KEY (id)
);

CREATE TABLE presentation_slide
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    template_slide_id BIGINT                                  NOT NULL,
    presentation_id   BIGINT                                  NOT NULL,
    order_number      INTEGER                                 NOT NULL,
    CONSTRAINT pk_presentation_slide PRIMARY KEY (id)
);

CREATE TABLE slide_field
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value                   JSONB                                   NOT NULL,
    image_id                BIGINT,
    template_slide_field_id BIGINT                                  NOT NULL,
    slide_id                BIGINT                                  NOT NULL,
    CONSTRAINT pk_slide_field PRIMARY KEY (id)
);

CREATE TABLE template_presentation
(
    id   BIGINT       NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_template_presentation PRIMARY KEY (id)
);

CREATE TABLE template_slide
(
    id                       BIGINT       NOT NULL,
    type                     VARCHAR(255) NOT NULL,
    name                     VARCHAR(255) NOT NULL,
    description              TEXT NOT NULL,
    layout_id                INTEGER      NOT NULL,
    template_presentation_id BIGINT       NOT NULL,
    CONSTRAINT pk_template_slide PRIMARY KEY (id)
);

CREATE TABLE template_slide_field
(
    id                BIGINT       NOT NULL,
    content_type      VARCHAR(255) NOT NULL,
    name              VARCHAR(255) NOT NULL,
    schema_key        VARCHAR(255) NOT NULL,
    description       VARCHAR(255) NOT NULL,
    example           JSONB        NOT NULL,
    meta              JSONB        NOT NULL,
    shape_name        VARCHAR(255) NOT NULL,
    template_slide_id BIGINT       NOT NULL,
    CONSTRAINT pk_template_slide_field PRIMARY KEY (id)
);

ALTER TABLE template_slide
    ADD CONSTRAINT uc_57a9a70ccab3c288677900af0 UNIQUE (template_presentation_id, type);

ALTER TABLE template_slide_field
    ADD CONSTRAINT uc_af9fcba89a9f45737af1df92b UNIQUE (template_slide_id, schema_key);

ALTER TABLE presentation_slide
    ADD CONSTRAINT uc_f3b8071584c3c03e49ee017e4 UNIQUE (id);

ALTER TABLE template_slide
    ADD CONSTRAINT uc_template_slide_type UNIQUE (type);

ALTER TABLE presentation
    ADD CONSTRAINT FK_PRESENTATION_ON_TEMPLATE_PRESENTATION FOREIGN KEY (template_presentation_id) REFERENCES template_presentation (id);

ALTER TABLE presentation_slide
    ADD CONSTRAINT FK_PRESENTATION_SLIDE_ON_PRESENTATION FOREIGN KEY (presentation_id) REFERENCES presentation (id);

ALTER TABLE presentation_slide
    ADD CONSTRAINT FK_PRESENTATION_SLIDE_ON_TEMPLATE_SLIDE FOREIGN KEY (template_slide_id) REFERENCES template_slide (id);

ALTER TABLE slide_field
    ADD CONSTRAINT FK_SLIDE_FIELD_ON_IMAGE FOREIGN KEY (image_id) REFERENCES image (id);

ALTER TABLE slide_field
    ADD CONSTRAINT FK_SLIDE_FIELD_ON_SLIDE FOREIGN KEY (slide_id) REFERENCES presentation_slide (id);

ALTER TABLE slide_field
    ADD CONSTRAINT FK_SLIDE_FIELD_ON_TEMPLATE_SLIDE_FIELD FOREIGN KEY (template_slide_field_id) REFERENCES template_slide_field (id);

ALTER TABLE template_slide_field
    ADD CONSTRAINT FK_TEMPLATE_SLIDE_FIELD_ON_TEMPLATE_SLIDE FOREIGN KEY (template_slide_id) REFERENCES template_slide (id);

ALTER TABLE template_slide
    ADD CONSTRAINT FK_TEMPLATE_SLIDE_ON_TEMPLATE_PRESENTATION FOREIGN KEY (template_presentation_id) REFERENCES template_presentation (id);