CREATE TABLE template_presentation
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_template_presentation PRIMARY KEY (id)
);

CREATE TABLE template_presentation_slide
(
    presentation_template_id BIGINT NOT NULL,
    slide_template_id        BIGINT NOT NULL
);

CREATE TABLE template_slide
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type   VARCHAR(255)                            NOT NULL,
    name   VARCHAR(255)                            NOT NULL,
    prompt VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_template_slide PRIMARY KEY (id)
);

CREATE TABLE template_slide_field
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type              VARCHAR(255)                            NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    json_key          VARCHAR(255)                            NOT NULL,
    prompt            VARCHAR(255)                            NOT NULL,
    example           VARCHAR(255)                            NOT NULL,
    template_slide_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_template_slide_field PRIMARY KEY (id)
);

ALTER TABLE template_slide
    ADD CONSTRAINT uc_template_slide_type UNIQUE (type);

ALTER TABLE template_slide_field
    ADD CONSTRAINT FK_TEMPLATE_SLIDE_FIELD_ON_TEMPLATE_SLIDE FOREIGN KEY (template_slide_id) REFERENCES template_slide (id);

ALTER TABLE template_presentation_slide
    ADD CONSTRAINT fk_tempresli_on_template_presentation FOREIGN KEY (presentation_template_id) REFERENCES template_presentation (id);

ALTER TABLE template_presentation_slide
    ADD CONSTRAINT fk_tempresli_on_template_slide FOREIGN KEY (slide_template_id) REFERENCES template_slide (id);
