CREATE TABLE image
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_image PRIMARY KEY (id)
);

CREATE TABLE presentation
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                      VARCHAR(255)                            NOT NULL,
    created_at                TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at                TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    template_presentation__id BIGINT                                  NOT NULL,
    CONSTRAINT pk_presentation PRIMARY KEY (id)
);

CREATE TABLE presentation_slide
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    template_slide_id BIGINT                                  NOT NULL,
    presentation_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_presentation_slide PRIMARY KEY (id)
);

CREATE TABLE slide_field
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    value                   VARCHAR(255),
    "order"                 INTEGER,
    image_id                BIGINT                                  NOT NULL,
    template_slide_field_id BIGINT                                  NOT NULL,
    slide_id                BIGINT                                  NOT NULL,
    CONSTRAINT pk_slide_field PRIMARY KEY (id)
);

ALTER TABLE presentation
    ADD CONSTRAINT FK_PRESENTATION_ON_TEMPLATE_PRESENTATION_ FOREIGN KEY (template_presentation__id) REFERENCES template_presentation (id);

ALTER TABLE presentation_slide
    ADD CONSTRAINT FK_PRESENTATION_SLIDE_ON_PRESENTATION FOREIGN KEY (presentation_id) REFERENCES presentation (id);

ALTER TABLE presentation_slide
    ADD CONSTRAINT FK_PRESENTATION_SLIDE_ON_TEMPLATE_SLIDE FOREIGN KEY (template_slide_id) REFERENCES template_slide (id);

ALTER TABLE slide_field
    ADD CONSTRAINT FK_SLIDE_FIELD_ON_IMAGE FOREIGN KEY (image_id) REFERENCES image (id);

ALTER TABLE slide_field
    ADD CONSTRAINT FK_SLIDE_FIELD_ON_SLIDE FOREIGN KEY (slide_id) REFERENCES presentation_slide (id);

ALTER TABLE slide_field
    ADD CONSTRAINT FK_SLIDE_FIELD_ON_TEMPLATE_SLIDE_FIELD FOREIGN KEY (template_slide_field_id) REFERENCES template_slide_field (id);