CREATE TABLE template_image
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    width  INTEGER,
    height INTEGER,
    CONSTRAINT pk_template_image PRIMARY KEY (id)
);

ALTER TABLE template_slide_field
    ADD template_image_id BIGINT;

ALTER TABLE template_slide_field
    ADD CONSTRAINT uc_template_slide_field_template_image UNIQUE (template_image_id);

ALTER TABLE template_slide_field
    ADD CONSTRAINT FK_TEMPLATE_SLIDE_FIELD_ON_TEMPLATE_IMAGE FOREIGN KEY (template_image_id) REFERENCES template_image (id);

-- правим данные
INSERT INTO template_image(width, height)
VALUES (512, 512);

UPDATE template_slide_field
SET template_image_id=1
WHERE type = 'IMAGE';
