CREATE TABLE template_shape_position
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    x      DOUBLE PRECISION,
    y      DOUBLE PRECISION,
    width  DOUBLE PRECISION,
    height DOUBLE PRECISION,
    CONSTRAINT pk_template_shape_position PRIMARY KEY (id)
);

CREATE TABLE template_text
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    font_family VARCHAR(255),
    font_size   DOUBLE PRECISION,
    font_style  VARCHAR(255),
    font_color  VARCHAR(255),
    position_id BIGINT,
    CONSTRAINT pk_template_text PRIMARY KEY (id)
);

ALTER TABLE template_slide
    ADD layout_id INTEGER;

ALTER TABLE template_image
    ADD position_id BIGINT;

ALTER TABLE template_image
    ADD CONSTRAINT uc_template_image_position UNIQUE (position_id);

ALTER TABLE template_text
    ADD CONSTRAINT uc_template_text_position UNIQUE (position_id);

ALTER TABLE template_image
    ADD CONSTRAINT FK_TEMPLATE_IMAGE_ON_POSITION FOREIGN KEY (position_id) REFERENCES template_shape_position (id);

ALTER TABLE template_text
    ADD CONSTRAINT FK_TEMPLATE_TEXT_ON_POSITION FOREIGN KEY (position_id) REFERENCES template_shape_position (id);
